# -*- coding: utf-8 -*-
"""tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8817sPsJRyDatpZ2hmPunP169cNPFZX
"""

# Hardcoded stock prices
stock_prices = {"AAPL": 180, "TSLA": 250, "GOOGL": 2800, "MSFT": 300}

print("Welcome to Stock Portfolio Tracker")
print("Available stocks:", ", ".join(stock_prices.keys()))

portfolio = {}
total_investment = 0

while True:
    stock = input("\nEnter stock symbol (or type 'done' to finish): ").upper()
    if stock == 'DONE':
        break
    if stock not in stock_prices:
        print("Stock not found. Try again.")
        continue
    try:
        qty = int(input(f"Enter quantity for {stock}: "))
        portfolio[stock] = portfolio.get(stock, 0) + qty
    except ValueError:
        print("Please enter a valid number.")

# Calculate total
print("\n--- Portfolio Summary ---")
for stock, qty in portfolio.items():
    value = qty * stock_prices[stock]
    total_investment += value
    print(f"{stock}: {qty} shares x ${stock_prices[stock]} = ${value}")

print(f"\nTotal Investment Value: ${total_investment}")

# Optional: save to txt file
save = input("\nSave to file? (y/n): ").lower()
if save == 'y':
    with open("portfolio.txt", "w") as f:
        f.write("Stock Portfolio Summary\n")
        for stock, qty in portfolio.items():
            f.write(f"{stock}: {qty} shares x ${stock_prices[stock]} = ${qty * stock_prices[stock]}\n")
        f.write(f"\nTotal Investment Value: ${total_investment}\n")
    print("Saved to portfolio.txt")
